# ┏━━━━━━┓
# ┃ font ┃
# ┗━━━━━━┛

[font]
size = 10.0

[font.offset]
x = 0
y = 1

[font.normal]
family = 'SauceCodePro Nerd Font Mono'
style = 'Regular'

[font.italic]
family = 'SauceCodePro Nerd Font Mono'
style = 'Italic'

[font.bold]
family = 'SauceCodePro Nerd Font Mono'
style = 'Bold'

[font.bold_italic]
family = 'SauceCodePro Nerd Font Mono'
style = 'Bold Italic'
