# ═════════════════════════════════════
# ░█  ░█ ▀█▀ ░█▄ ░█ ░█▀▀▄ ░█▀▀▀█ ░█  ░█
# ░█░█░█ ░█  ░█░█░█ ░█ ░█ ░█  ░█ ░█░█░█
# ░█▄▀▄█ ▄█▄ ░█  ▀█ ░█▄▄▀ ░█▄▄▄█ ░█▄▀▄█
# ═════════════════════════════════════

[window]
decorations = 'None'
dynamic_padding = true

[window.padding]
x = 4
y = 4
