#!/usr/bin/env bash

# ┏━━━━━━━━━┓
# ┃ globals ┃
# ┗━━━━━━━━━┛

readonly TMUX_CONFIG_DIRECTORY_PATH="$(tmux display-message -p "#{config_files}" | xargs dirname)"

readonly -A COMPONENTS=(
  ["SESSION"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/session)"
  ["CURRENT_WINDOW"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/current_window #{window_index} #{pane_index})"
  ["WINDOW"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/window #{window_index} #{pane_index})"
  ["GIT"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/git)"
  ["PATH"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/path)"
  ["UPTIME"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/uptime)"
  ["USER"]="#(${TMUX_CONFIG_DIRECTORY_PATH}/status/components/user)"
)

readonly -A NUMBER_FORMATS=(
  ["DIGITAL"]="🯰🯱🯲🯳🯴🯵🯶🯷🯸🯹"
  ["HOLLOW_SQUARE"]="󰎣󰎦󰎩󰎬󰎮󰎰󰎵󰎸󰎻󰎾"
  ["HOLLOW_DOUBLE_SQUARE"]="󰎢󰎥󰎨󰎫󰎲󰎯󰎴󰎷󰎺󰎽"
)

readonly -A ICONS=(
  ["PREFIX_INACTIVE"]="󰤂"
  ["PREFIX_ACTIVE"]="󰪥"
  ["WINDOW"]=""
  ["DOT"]=""
  ["RESTORE"]="󰁯"
  ["BRANCH"]="󰘬"
  ["BRANCH_DIRTY"]="󱓎"
  ["ARROW_UP"]=""
  ["ARROW_DOWN"]=""
  ["ASTERISK"]=""
  ["PLUS"]=""
  ["MINUS"]=""
  ["QUESTION_MARK"]="?"
  ["FOLDER"]=""
  ["TIMER"]="󰔟"
  ["USER"]=""
  ["SHADE"]="░"
)

declare -A COLORS=(
  ["BACKGROUND_0"]="#0C0C0C"
  ["BACKGROUND_1"]="#161616"
  ["BACKGROUND_2"]="#252525"
  ["BACKGROUND_3"]="#353535"
  ["BACKGROUND_4"]="#535353"
  ["FOREGROUND_0"]="#F9FBFF"
  ["FOREGROUND_1"]="#F2F4F8"
  ["FOREGROUND_2"]="#B6B8BB"
  ["FOREGROUND_3"]="#7B7C7E"
  ["BLACK"]="#282828"
  ["RED"]="#EE5396"
  ["GREEN"]="#25BE6A"
  ["YELLOW"]="#08BDBA"
  ["BLUE"]="#78A9FF"
  ["MAGENTA"]="#BE95FF"
  ["CYAN"]="#33B1FF"
)

COLORS["BACKGROUND"]="${COLORS["BACKGROUND_1"]}"
COLORS["FOREGROUND"]="${COLORS["FOREGROUND_1"]}"

readonly -A COLORS

convert_number_format() {
  local -r NUMBER="$1"
  local -r FORMAT="$2"

  if [[ -z "${FORMAT}" ]]; then
    echo "${NUMBER}"
    return
  fi

  if [[ ! "${#FORMAT}" -eq 10 ]]; then
    echo "${NUMBER}"
    return
  fi

  for ((index = 0; index < "${#NUMBER}"; index++)); do
    echo -n "${FORMAT:"${NUMBER:${index}:1}":1}"
  done
}
readonly -f convert_number
