local map = require('core.utils').map

map('n', '<Tab>', ':BufferLineCycleNext<CR>')
map('n', '<S-Tab>', ':BufferLineCyclePrev<CR>')
map('n', '<leader><Tab>', ':BufferLineMoveNext<CR>')
map('n', '<leader><S-Tab>', ' :BufferLineMovePrev<CR>')
map('n', '<leader>1', ':BufferLineGoToBuffer 1<CR>')
map('n', '<leader>2', ':BufferLineGoToBuffer 2<CR>')
map('n', '<leader>3', ':BufferLineGoToBuffer 3<CR>')
map('n', '<leader>4', ':BufferLineGoToBuffer 4<CR>')
map('n', '<leader>5', ':BufferLineGoToBuffer 5<CR>')
map('n', '<leader>6', ':BufferLineGoToBuffer 6<CR>')
map('n', '<leader>7', ':BufferLineGoToBuffer 7<CR>')
map('n', '<leader>8', ':BufferLineGoToBuffer 8<CR>')
map('n', '<leader>9', ':BufferLineGoToBuffer 9<CR>')
