# ════════════════════════════════
# ░█ ░█ ░█▀▀▀█ ░█▀▀▀█ ░█ ▄▀ ░█▀▀▀█
# ░█▀▀█ ░█  ░█ ░█  ░█ ░█▀▄   ▀▀▀▄▄
# ░█ ░█ ░█▄▄▄█ ░█▄▄▄█ ░█ ░█ ░█▄▄▄█
# ════════════════════════════════

set -g session-created "run renumber_tmux_sessions"
set -g session-closed "run renumber_tmux_sessions"
