# ════════════════════════════════════════════════════════════
# ░█▀▀█ ░█▄ ░█ ▀█▀ ░█▀▄▀█  █▀▀█ ▀▀█▀▀ ▀█▀ ░█▀▀▀█ ░█▄ ░█ ░█▀▀▀█
# ░█▄▄█ ░█░█░█ ░█  ░█░█░█ ░█▄▄█  ░█   ░█  ░█  ░█ ░█░█░█  ▀▀▀▄▄
# ░█ ░█ ░█  ▀█ ▄█▄ ░█  ░█ ░█ ░█  ░█   ▄█▄ ░█▄▄▄█ ░█  ▀█ ░█▄▄▄█
# ════════════════════════════════════════════════════════════

# █▀▀ █ █ █▀█ █ █ █▀▀ █▀
# █▄▄ █▄█ █▀▄ ▀▄▀ ██▄ ▄█

bezier = easeOutQuart, 0.190, 0.91, 0.37, 1

# █ █ █ █ █▄ █ █▀▄ █▀█ █ █ █ █▀
# ▀▄▀▄▀ █ █ ▀█ █▄▀ █▄█ ▀▄▀▄▀ ▄█

animation = windows, 1, 5, easeOutQuart, slide
animation = windowsIn, 1, 5, easeOutQuart, popin
animation = windowsOut, 1, 5, easeOutQuart, popin 70%

# █▀▀ █▀█ █▀▄ █▀▀
# █▀  █▀█ █▄▀ ██▄

animation = fade, 1, 5, easeOutQuart
animation = fadeIn, 1, 5, easeOutQuart
animation = fadeOut, 1, 5, easeOutQuart

# █ █ █ █▀█ █▀█ █▄▀ █▀ █▀█ █▀█ █▀▀ █▀▀ █▀
# ▀▄▀▄▀ █▄█ █▀▄ █ █ ▄█ █▀▀ █▀█ █▄▄ ██▄ ▄█

animation = workspaces, 1, 5, easeOutQuart, slide
animation = specialWorkspace, 1, 5, easeOutQuart, slidevert
